spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/katibaai
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text
      chat:
        options:
          model: qwen2.5:7b

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-minutes: ${JWT_EXPIRY_MINUTES}
    refresh-days: ${JWT_REFRESH_DAYS}


