spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/katibaai
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
