spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/katibaai
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-minutes: ${JWT_EXPIRY_MINUTES}
    refresh-days: ${JWT_REFRESH_DAYS}

  flyway:
    enabled: true
